### ISSUE TITLE
Set default CPU to `avr2`

### ISSUE THREAD

**Issue by dylanmckay** [dylanmckay/avr-llvm#17]
To be compatible with AVR-GCC

**Comment by 4ntoine** [comment]
if the idea is to set default CPU for AVR target for `llc` tool then one can just add:
```
  // set avr2 as default CPU for AVR target
  if (MCPU.empty() && MArch == "avr") {
    MCPU = "avr2";
  }
```
to https://github.com/dylanmckay/avr-llvm/blob/avr-support/tools/llc/llc.cpp#L218

**Comment by 4ntoine** [comment]
or edit https://github.com/dylanmckay/avr-llvm/blob/avr-support/lib/Target/AVR/AVRTargetMachine.cpp#L28 and https://github.com/dylanmckay/avr-llvm/blob/avr-support/lib/Target/AVR/AVRTargetMachine.cpp#L29 to smth like
```
LLVMTargetMachine(T, TT, (CPU.empty() ? "avr2" : CPU), FS, Options, RM, CM, OL),
SubTarget(TT, (CPU.empty() ? "avr2" : CPU), FS, *this)
```

**Comment by dylanmckay** [comment]
Ah, I had forgotten where abouts that last snippet was in the code. I'm currently at work, but if you want to add that in and submit a pull request, I will accept it.

**Comment by dylanmckay** [comment]
I'm talking about the AVRTargetMachine class edit that you suggested
