### ISSUE TITLE
Create `Quick Start` Wiki page

### ISSUE THREAD

**Issue by dylanmckay** [dylanmckay/avr-llvm#5]
Create a Wiki page detailing how to compile a file using clang and produce AVR assembly from it.

**Comment by RandomInsano** [comment]
Watching now. Let me know when there's something to play with.

**Comment by dylanmckay** [comment]
I have created a wiki page outlining the directory structure. It goes into some detail about the inner workings of the backend, but these descriptions should eventually be moved into their own pages.

**Comment by RandomInsano** [comment]
Slick. I'll give it a read over. How do I actually get to using this stuff? I'm expecting to just build it, but what I'm I supplying in? LLVM IR? What comes out? Assembly? I'm hoping machine code.

**Comment by dylanmckay** [comment]
Added a quick start guide, see [Getting Started](https://github.com/dylanmckay/avr-llvm/wiki/Getting-Started).

**Comment by dylanmckay** [comment]
> ll give it a read over. How do I actually get to using this stuff? I'm expecting to just build it, but what I'm I supplying in? LLVM IR?
The getting started guide should explain this now.

> What comes out? Assembly? I'm hoping machine code
Assembly code or machine code, depending on what flags you pass to the compiler.

**Comment by 4ntoine** [comment]
For some reason i can't edit it (https://github.com/dylanmckay/avr-llvm/wiki/Getting-Started).

Link to 4ntoine/clang is broken: 'https://github.com/dylanmckay/avr-llvm/wiki/github.com/4ntoine/clang.git' is shown instead of 'https://github.com/4ntoine/clang'

**Comment by dylanmckay** [comment]
> For some reason i can't edit it 
I just enabled public editing

**Comment by dylanmckay** [comment]
I just prefixed the links with `https://` now.

**Comment by 4ntoine** [comment]
Fixed, thanks
